# Generated by Django 2.2.24 on 2022-08-21 18:07

from django.db import migrations
import phonenumbers


def set_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.parse(
            flat.owners_phonenumber,
            'RU',
        )
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().updade(owner_pure_phone='')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220821_2042'),
    ]

    operations = [
        migrations.RunPython(set_owner_pure_phone, move_backward)
    ]
