# Generated by Django 2.2.24 on 2022-08-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220828_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_deprecated',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
