# Generated by Django 2.2.24 on 2022-08-28 14:53

from django.db import migrations


def set_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner.flats.set(Flat.objects.filter(owner_deprecated=owner.owner))
        owner.save()


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.update(flats=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220828_1753'),
    ]

    operations = [
        migrations.RunPython(set_owners, move_backward)
    ]
