# Generated by Django 2.2.24 on 2022-08-31 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_flat_owner_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.Flat', verbose_name='Квартира, на которую пожаловались'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
