# Generated by Django 2.2.24 on 2022-08-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20220831_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='complain_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='complain',
            old_name='complain_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
