# Generated by Django 2.2.24 on 2022-09-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20220903_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='address',
            new_name='flat',
        ),
    ]
